#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sh -c "rclone --vfs-cache-mode writes mount \"one drive\": ~/OneDrive"
#bash ~/.config/polybar/launch.sh --forest
~/.config/polybar/forest/launch.sh &

#bspc monitor DVI-D-0 -d I II III IV V
bspc monitor DVI-D-0 -d code office graphics mail web
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config bottom_padding 30
bspc config top_padding 30
bspc config left_padding 30
bspc config right_padding 30

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
feh --bg-fill /home/lee/Pictures/Wallpapers/wooded-sunrise.jpg
#picom --experimental-backends &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
mpd &
dunst &
numlockx &
